---
- name: Prometheus node exporter deploy
  hosts: wn11
#  hosts: [cluster_wn]
#  hosts: 10.0.0.46
  gather_facts: no



  tasks:

  - name: Ping Pong
    ping:

  - name: Add system user prometheus
    user:
      name: prometheus
      shell: /usr/sbin/nologin
      system: true
      create_home: false
      comment: Prometheus system user

  - name: Download and Unarchive prometheus-node-exporter-1.8
    unarchive:
      src: https://github.com/prometheus/node_exporter/releases/download/v1.8.0/node_exporter-1.8.0.linux-amd64.tar.gz
      dest: /tmp/
      remote_src: true

  - name: Copy node-exporter binary file to /usr/bin/ named "prometheus-node-exporter"
    copy:
      src: /tmp/node_exporter-1.8.0.linux-amd64/node_exporter
      dest: /usr/bin/prometheus-node-exporter
      mode: '755'
      remote_src: true

  - name: Copy prometheus node exporter service file to
    get_url:
      url: http://10.0.0.104/distr/prometheus-node-exporter-service/prometheus-node-exporter.service
      dest: /usr/lib/systemd/system/
      mode: '644'

  - name: Just force systemd to reread configs
    systemd:
      daemon_reload: true

  - name: Start prometheus node exporter service and Make service start on boot
    systemd:
      name: prometheus-node-exporter.service
      state: started
      enabled: true



- name: PLAY - Actions on Ubuntu desktop
#  hosts: mgmt
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:

  - name: Find and replace line in /etc/prometheus/prometheus.yml
    lineinfile:
      path: /etc/prometheus/prometheus.yml
      regexp: "^      - targets: \\['desktop"
      line: "      - targets: ['desktop:9100','10.0.0.105:9100','10.0.0.106:9100','10.0.0.107:9100','10.0.0.108:9100','10.0.0.109:9100','10.0.0.110:9100','10.0.0.111:9100','10.0.0.112:9100','10.0.0.113:9100','10.0.0.114:9100','10.0.0.115:9100','10.0.0.116:9100','10.0.0.117:9100','10.0.0.118:9100','10.0.0.119:9100','10.0.0.120:9100','10.0.0.121:9100','10.0.0.122:9100','10.0.0.123:9100','10.0.0.124:9100','10.0.0.125:9100','10.0.0.129:9100','10.0.0.131:9100','10.0.0.131:9100','10.0.0.132:9100','10.0.0.133:9100','10.0.0.134:9100','10.0.0.135:9100','10.0.0.136:9100','10.0.0.46:9100']"
      backup: yes
    notify: Restart prometheus.service



  handlers:
  - name: Restart prometheus.service
    systemd:
      name: prometheus.service
      state: restarted
